/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type SubmissionFormStep3OverridesProps = {
    "1"?: PrimitiveOverrideProps<TextProps>;
    "2"?: PrimitiveOverrideProps<TextProps>;
    "3"?: PrimitiveOverrideProps<TextProps>;
    "4"?: PrimitiveOverrideProps<TextProps>;
    "5"?: PrimitiveOverrideProps<TextProps>;
    "6"?: PrimitiveOverrideProps<TextProps>;
    SubmissionFormStep3?: PrimitiveOverrideProps<ViewProps>;
    SubmissionFormStep2?: PrimitiveOverrideProps<ViewProps>;
    "Get a project quote"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 4276"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37319"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37147"?: PrimitiveOverrideProps<ViewProps>;
    "Please fill in your information below."?: PrimitiveOverrideProps<TextProps>;
    "Group 3714638382723"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 43238382724"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427738382725"?: PrimitiveOverrideProps<ViewProps>;
    "How does the proposed project meet purposes of the Legislation? Select All That Apply"?: PrimitiveOverrideProps<TextProps>;
    "Project Type: Select All That Apply"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 43538382730"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427838382731"?: PrimitiveOverrideProps<ViewProps>;
    "Miles of Road Maintained"?: PrimitiveOverrideProps<TextProps>;
    "Miles of road decommissioned/obliterated:"?: PrimitiveOverrideProps<TextProps>;
    "Group 37326"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3714638382778"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 43238382779"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427738382780"?: PrimitiveOverrideProps<ViewProps>;
    "Number of structures maintained/improved:"?: PrimitiveOverrideProps<TextProps>;
    "Acres of soil productivity improved:"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 43538382785"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427838382786"?: PrimitiveOverrideProps<ViewProps>;
    "Miles of stream/river restored/improved:"?: PrimitiveOverrideProps<TextProps>;
    "Miles of fish habitat restored/improved:"?: PrimitiveOverrideProps<TextProps>;
    "Please fill the form below to receive a quote for your project. Feel free to add as much detail as needed."?: PrimitiveOverrideProps<TextProps>;
    "Line 133"?: PrimitiveOverrideProps<IconProps>;
    "Primary BTN"?: PrimitiveOverrideProps<FlexProps>;
    "Button Text38382742"?: PrimitiveOverrideProps<TextProps>;
    "Secondary BTN"?: PrimitiveOverrideProps<FlexProps>;
    "Button Text38382744"?: PrimitiveOverrideProps<TextProps>;
    "Frame 326"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 327"?: PrimitiveOverrideProps<FlexProps>;
    "Group 37318"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4354"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4355"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 435638204234"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37135"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37133"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 435"?: PrimitiveOverrideProps<IconProps>;
    "Group 37132"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37131"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 436"?: PrimitiveOverrideProps<IconProps>;
    "Group 37138"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713738204244"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43738204245"?: PrimitiveOverrideProps<IconProps>;
    "Group 37139"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713738204248"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43738204249"?: PrimitiveOverrideProps<IconProps>;
    "Group 3714038204251"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713738204252"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43738204253"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 4357"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 435638204256"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37329"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3714638382824"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 43238382825"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427738382826"?: PrimitiveOverrideProps<ViewProps>;
    "Timber volume generated (mbf):"?: PrimitiveOverrideProps<TextProps>;
    "Jobs generated in full time equivalents (FTE) to nearest tenth. One FTE is 52 forty hour weeks:"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 43538382829"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4279"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427838382830"?: PrimitiveOverrideProps<ViewProps>;
    "People reached (for environmental education projects/fire prevention):"?: PrimitiveOverrideProps<TextProps>;
    "Direct economic activity benefit:"?: PrimitiveOverrideProps<TextProps>;
    "Other:"?: PrimitiveOverrideProps<TextProps>;
    "Group 37327"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3714638382796"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 43238382797"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427738382798"?: PrimitiveOverrideProps<ViewProps>;
    "Acres of native species reestablished:"?: PrimitiveOverrideProps<TextProps>;
    "Acres of hazardous fuel treatment"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 43538382801"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427838382802"?: PrimitiveOverrideProps<ViewProps>;
    "Miles of trail maintained:"?: PrimitiveOverrideProps<TextProps>;
    "Miles of trail obliterated:"?: PrimitiveOverrideProps<TextProps>;
    "Group 37328"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3714638382810"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 43238382811"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427738382812"?: PrimitiveOverrideProps<ViewProps>;
    "Acres of forest health improved (including fuels reduction):"?: PrimitiveOverrideProps<TextProps>;
    "Acres of rangeland improved:"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 43538382815"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427838382816"?: PrimitiveOverrideProps<ViewProps>;
    "Acres of wildlife habitat restored/improved:"?: PrimitiveOverrideProps<TextProps>;
    "Acres of noxious weeds controlled:"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 4359"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3714038393134"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713738393135"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43738393136"?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type SubmissionFormStep3Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: SubmissionFormStep3OverridesProps | undefined | null;
}>;
export default function SubmissionFormStep3(props: SubmissionFormStep3Props): React.ReactElement;
