/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type SubmissionFormStep2OverridesProps = {
    "1"?: PrimitiveOverrideProps<TextProps>;
    "2"?: PrimitiveOverrideProps<TextProps>;
    "3"?: PrimitiveOverrideProps<TextProps>;
    "4"?: PrimitiveOverrideProps<TextProps>;
    "5"?: PrimitiveOverrideProps<TextProps>;
    "6"?: PrimitiveOverrideProps<TextProps>;
    SubmissionFormStep2?: PrimitiveOverrideProps<ViewProps>;
    "Get a project quote"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 4276"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37319"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3714637662775"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 43237662776"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 323"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427737662777"?: PrimitiveOverrideProps<ViewProps>;
    "Type Goals Here:"?: PrimitiveOverrideProps<TextProps>;
    "One Sentence Description:"?: PrimitiveOverrideProps<TextProps>;
    "Project Goals and Objective"?: PrimitiveOverrideProps<TextProps>;
    "Project Description"?: PrimitiveOverrideProps<TextProps>;
    "Group 37147"?: PrimitiveOverrideProps<ViewProps>;
    "Please fill in your information below."?: PrimitiveOverrideProps<TextProps>;
    "Group 3714637662497"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 43237662498"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427737662499"?: PrimitiveOverrideProps<ViewProps>;
    "Austin, Texas"?: PrimitiveOverrideProps<TextProps>;
    "Ex: Shenandoah National Park"?: PrimitiveOverrideProps<TextProps>;
    "Project Location"?: PrimitiveOverrideProps<TextProps>;
    "National Forest(s)"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 435"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427837662511"?: PrimitiveOverrideProps<ViewProps>;
    "Ex: Region 1"?: PrimitiveOverrideProps<TextProps>;
    "T1N-R1E-12"?: PrimitiveOverrideProps<TextProps>;
    "Forest Service District"?: PrimitiveOverrideProps<TextProps>;
    "Location: Township-range-section"?: PrimitiveOverrideProps<TextProps>;
    Group?: PrimitiveOverrideProps<ViewProps>;
    Vector37662813?: PrimitiveOverrideProps<IconProps>;
    Vector37662814?: PrimitiveOverrideProps<IconProps>;
    "Please fill the form below to receive a quote for your project. Feel free to add as much detail as needed."?: PrimitiveOverrideProps<TextProps>;
    "Line 133"?: PrimitiveOverrideProps<IconProps>;
    "Primary BTN"?: PrimitiveOverrideProps<FlexProps>;
    "Button Text37662551"?: PrimitiveOverrideProps<TextProps>;
    "Secondary BTN37662677"?: PrimitiveOverrideProps<FlexProps>;
    "Button Text37662678"?: PrimitiveOverrideProps<TextProps>;
    "Secondary BTN38394169"?: PrimitiveOverrideProps<FlexProps>;
    "Button Text38394170"?: PrimitiveOverrideProps<TextProps>;
    "Group 37321"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4355"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 435938203086"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4360"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 4361"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4356"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713538203090"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713338203091"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43538203092"?: PrimitiveOverrideProps<IconProps>;
    "Group 3713538203094"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713338203095"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43538203096"?: PrimitiveOverrideProps<IconProps>;
    "Group 37138"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713738203099"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43738203100"?: PrimitiveOverrideProps<IconProps>;
    "Group 3713938203102"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713738203103"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43738203104"?: PrimitiveOverrideProps<IconProps>;
    "Group 3713938203106"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713738203107"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43738203108"?: PrimitiveOverrideProps<IconProps>;
    "Group 37325"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427838203436"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37324"?: PrimitiveOverrideProps<ViewProps>;
    "Detailed:"?: PrimitiveOverrideProps<TextProps>;
    "Group 3714638352539"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 43238352540"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427738352541"?: PrimitiveOverrideProps<ViewProps>;
    "Yes/No"?: PrimitiveOverrideProps<TextProps>;
    State?: PrimitiveOverrideProps<TextProps>;
    "State/Private/Other lands involved?"?: PrimitiveOverrideProps<TextProps>;
    "If Yes, specify:"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 435938393128"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37140"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713738393130"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43738393131"?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type SubmissionFormStep2Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: SubmissionFormStep2OverridesProps | undefined | null;
}>;
export default function SubmissionFormStep2(props: SubmissionFormStep2Props): React.ReactElement;
