/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type SubmissionFormStep1OverridesProps = {
    "1"?: PrimitiveOverrideProps<TextProps>;
    "2"?: PrimitiveOverrideProps<TextProps>;
    "3"?: PrimitiveOverrideProps<TextProps>;
    "4"?: PrimitiveOverrideProps<TextProps>;
    "5"?: PrimitiveOverrideProps<TextProps>;
    "6"?: PrimitiveOverrideProps<TextProps>;
    SubmissionFormStep1?: PrimitiveOverrideProps<ViewProps>;
    SubmissionFormStep2?: PrimitiveOverrideProps<ViewProps>;
    "Get a project quote"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 4276"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 435938382887"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37319"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3714638203349"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 43238203350"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427738203351"?: PrimitiveOverrideProps<ViewProps>;
    "Group 4138203352"?: PrimitiveOverrideProps<ViewProps>;
    Vector38203353?: PrimitiveOverrideProps<IconProps>;
    Vector38203354?: PrimitiveOverrideProps<IconProps>;
    "01/01/2020"?: PrimitiveOverrideProps<TextProps>;
    "(123) 456 - 7890"?: PrimitiveOverrideProps<TextProps>;
    Date?: PrimitiveOverrideProps<TextProps>;
    "Phone Number"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 43538203359"?: PrimitiveOverrideProps<ViewProps>;
    "john.doe@gmail.com"?: PrimitiveOverrideProps<TextProps>;
    "Contact Email"?: PrimitiveOverrideProps<TextProps>;
    "Group 37147"?: PrimitiveOverrideProps<ViewProps>;
    "Please fill in your information below."?: PrimitiveOverrideProps<TextProps>;
    "Contact details"?: PrimitiveOverrideProps<TextProps>;
    "Group 3714638203365"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 43238203366"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 427738203367"?: PrimitiveOverrideProps<ViewProps>;
    Group38203368?: PrimitiveOverrideProps<ViewProps>;
    Vector38203369?: PrimitiveOverrideProps<IconProps>;
    Vector38203370?: PrimitiveOverrideProps<IconProps>;
    "Group 4138203371"?: PrimitiveOverrideProps<ViewProps>;
    Vector38203372?: PrimitiveOverrideProps<IconProps>;
    Vector38203373?: PrimitiveOverrideProps<IconProps>;
    "Waste Management"?: PrimitiveOverrideProps<TextProps>;
    Virginia?: PrimitiveOverrideProps<TextProps>;
    "Project Name"?: PrimitiveOverrideProps<TextProps>;
    State?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 43538203378"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4278"?: PrimitiveOverrideProps<ViewProps>;
    Group38203380?: PrimitiveOverrideProps<ViewProps>;
    Vector38203381?: PrimitiveOverrideProps<IconProps>;
    Vector38203382?: PrimitiveOverrideProps<IconProps>;
    "Prince William County"?: PrimitiveOverrideProps<TextProps>;
    "Company name"?: PrimitiveOverrideProps<TextProps>;
    "County(s)"?: PrimitiveOverrideProps<TextProps>;
    "Project Submitted By"?: PrimitiveOverrideProps<TextProps>;
    Group38203387?: PrimitiveOverrideProps<ViewProps>;
    Vector38203388?: PrimitiveOverrideProps<IconProps>;
    Vector38203389?: PrimitiveOverrideProps<IconProps>;
    Vector38203390?: PrimitiveOverrideProps<IconProps>;
    "Group 4138203391"?: PrimitiveOverrideProps<ViewProps>;
    Vector38203392?: PrimitiveOverrideProps<IconProps>;
    Vector38203393?: PrimitiveOverrideProps<IconProps>;
    "Please fill the form below to receive a quote for your project. Feel free to add as much detail as needed."?: PrimitiveOverrideProps<TextProps>;
    "Line 133"?: PrimitiveOverrideProps<IconProps>;
    "Primary BTN"?: PrimitiveOverrideProps<FlexProps>;
    "Button Text"?: PrimitiveOverrideProps<TextProps>;
    "Group 37321"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 435538203399"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 435938203400"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4356"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713538203404"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713838203427"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713738203428"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43738203429"?: PrimitiveOverrideProps<IconProps>;
    "Group 3713538203408"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37133"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 435"?: PrimitiveOverrideProps<IconProps>;
    "Group 3713838203412"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713738203413"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43738203414"?: PrimitiveOverrideProps<IconProps>;
    "Group 3713938203416"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713738203417"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43738203418"?: PrimitiveOverrideProps<IconProps>;
    "Group 3713938203420"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713738203421"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43738203422"?: PrimitiveOverrideProps<IconProps>;
    "Group 37140"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713738382889"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43738382890"?: PrimitiveOverrideProps<IconProps>;
    "Group 37322"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 435538203425"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4360"?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type SubmissionFormStep1Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: SubmissionFormStep1OverridesProps | undefined | null;
}>;
export default function SubmissionFormStep1(props: SubmissionFormStep1Props): React.ReactElement;
