/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type SubmissionFormStep2OverridesProps = {
    "1"?: PrimitiveOverrideProps<TextProps>;
    "2"?: PrimitiveOverrideProps<TextProps>;
    "3"?: PrimitiveOverrideProps<TextProps>;
    "4"?: PrimitiveOverrideProps<TextProps>;
    SubmissionFormStep2?: PrimitiveOverrideProps<ViewProps>;
    "Get a project quote"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 4276"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37318"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4354"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4355"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4357"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4356"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37135"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37133"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 435"?: PrimitiveOverrideProps<IconProps>;
    "Group 37132"?: PrimitiveOverrideProps<ViewProps>;
    "Group 37131"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 436"?: PrimitiveOverrideProps<IconProps>;
    "Group 37138"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713737662571"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43737662572"?: PrimitiveOverrideProps<IconProps>;
    "Group 37139"?: PrimitiveOverrideProps<ViewProps>;
    "Group 3713737662575"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 43737662576"?: PrimitiveOverrideProps<IconProps>;
    "Group 37147"?: PrimitiveOverrideProps<ViewProps>;
    "Please select which service you are interested in."?: PrimitiveOverrideProps<TextProps>;
    "Our services"?: PrimitiveOverrideProps<TextProps>;
    "Group 37146"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 432"?: PrimitiveOverrideProps<ViewProps>;
    Development?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 439"?: PrimitiveOverrideProps<IconProps>;
    Shadow37662585?: PrimitiveOverrideProps<ViewProps>;
    "Group 37290"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 174737662587"?: PrimitiveOverrideProps<ViewProps>;
    Group37662588?: PrimitiveOverrideProps<ViewProps>;
    Vector37662589?: PrimitiveOverrideProps<IconProps>;
    Vector37662590?: PrimitiveOverrideProps<IconProps>;
    Vector37662591?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 4280"?: PrimitiveOverrideProps<ViewProps>;
    Marketing?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 441"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 4279"?: PrimitiveOverrideProps<ViewProps>;
    "Web Design"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 440"?: PrimitiveOverrideProps<IconProps>;
    Shadow37662598?: PrimitiveOverrideProps<ViewProps>;
    "Group 37292"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 174737662600"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4293"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4294"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4295"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4296"?: PrimitiveOverrideProps<ViewProps>;
    Group37662605?: PrimitiveOverrideProps<ViewProps>;
    Vector37662606?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 4281"?: PrimitiveOverrideProps<ViewProps>;
    Other?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 442"?: PrimitiveOverrideProps<IconProps>;
    Shadow37662610?: PrimitiveOverrideProps<ViewProps>;
    Setting37662611?: PrimitiveOverrideProps<ViewProps>;
    "Group 4028"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 350"?: PrimitiveOverrideProps<IconProps>;
    Setting37662614?: PrimitiveOverrideProps<IconProps>;
    Path37662615?: PrimitiveOverrideProps<IconProps>;
    Path37662616?: PrimitiveOverrideProps<IconProps>;
    "Please fill the form below to receive a quote for your project. Feel free to add as much detail as needed."?: PrimitiveOverrideProps<TextProps>;
    "Line 133"?: PrimitiveOverrideProps<IconProps>;
    "Primary BTN"?: PrimitiveOverrideProps<FlexProps>;
    "Button Text37662620"?: PrimitiveOverrideProps<TextProps>;
    "Secondary BTN"?: PrimitiveOverrideProps<FlexProps>;
    "Button Text37662622"?: PrimitiveOverrideProps<TextProps>;
    Shadow37662623?: PrimitiveOverrideProps<IconProps>;
    "Group 37291"?: PrimitiveOverrideProps<ViewProps>;
    Vector37662625?: PrimitiveOverrideProps<IconProps>;
    Group37662626?: PrimitiveOverrideProps<ViewProps>;
    Vector37662627?: PrimitiveOverrideProps<IconProps>;
    Vector37662628?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type SubmissionFormStep2Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: SubmissionFormStep2OverridesProps | undefined | null;
}>;
export default function SubmissionFormStep2(props: SubmissionFormStep2Props): React.ReactElement;
