// @ts-check
import { initSchema } from '@aws-amplify/datastore';
import { schema } from './schema';

const FailureRemedies = {
  "UNUSED_FUNDS_RETURNED": "UNUSED_FUNDS_RETURNED",
  "OTHER": "OTHER"
};

const MonitoringPlan = {
  "DESCRIBE_PROCES_PLAN": "DESCRIBE_PROCES_PLAN",
  "WHO_CONDUCTS_MONITORING": "WHO_CONDUCTS_MONITORING",
  "TOTAL_FUNDING_NEEDED": "TOTAL_FUNDING_NEEDED"
};

const ProjectCost = {
  "TITLE2_FUNDS_REQUESTED": "TITLE2_FUNDS_REQUESTED",
  "IS_MULTIYEAR_FUNDING": "IS_MULTIYEAR_FUNDING"
};

const AccomplishmentMethods = {
  "CONTRACT": "CONTRACT",
  "FEDERAL_WORKFORCE": "FEDERAL_WORKFORCE",
  "COUNTY_WORKFORCE": "COUNTY_WORKFORCE",
  "VOLUNTEERS": "VOLUNTEERS",
  "GRANT": "GRANT",
  "AGREEMENT": "AGREEMENT",
  "AMERICORPS": "AMERICORPS",
  "YCC_CCC_CREWS": "YCC_CCC_CREWS",
  "JOB_CORPS": "JOB_CORPS",
  "STEWARDSHIP_CONTRACT": "STEWARDSHIP_CONTRACT",
  "MERCHANTABLE_TIMBER_PLOT": "MERCHANTABLE_TIMBER_PLOT",
  "OTHER": "OTHER"
};

const ProjectAccomplishments = {
  "MILES_ROAD_MAINTAINED": "MILES_ROAD_MAINTAINED",
  "MILES_ROAD_DECOMISSIONED": "MILES_ROAD_DECOMISSIONED",
  "NUMBER_STRUCTURES_MAINTAINED": "NUMBER_STRUCTURES_MAINTAINED",
  "ACRES_OF_SOIL_PRODUCTIVITY_IMPROVED": "ACRES_OF_SOIL_PRODUCTIVITY_IMPROVED",
  "MILES_RIVER_IMPROVED": "MILES_RIVER_IMPROVED",
  "MILES_FISH_HABITAT": "MILES_FISH_HABITAT",
  "ACRES_NATIVE_SPECIES": "ACRES_NATIVE_SPECIES",
  "ACRES_HAZARDOUS_FUEL_TREATMENT": "ACRES_HAZARDOUS_FUEL_TREATMENT",
  "MILES_TRAIL_MAINTAINED": "MILES_TRAIL_MAINTAINED",
  "MILES_TRAIL_OBLITERATED": "MILES_TRAIL_OBLITERATED",
  "ACRES_FOREST_HEALTH_IMPROVED": "ACRES_FOREST_HEALTH_IMPROVED",
  "ACRES_RANGELAND_IMPROVED": "ACRES_RANGELAND_IMPROVED",
  "ACRES_WILDLIFE_RESTORED": "ACRES_WILDLIFE_RESTORED",
  "ACRES_NOXIOUS_WEED_CONTROLLED": "ACRES_NOXIOUS_WEED_CONTROLLED",
  "TIMBER_VOLUME_GENERATED": "TIMBER_VOLUME_GENERATED",
  "JOBS_GENERATED_FTE": "JOBS_GENERATED_FTE",
  "PEOPLE_REACHED": "PEOPLE_REACHED",
  "DIRECT_ECONOMIC_BENEFIT": "DIRECT_ECONOMIC_BENEFIT",
  "OTHER": "OTHER"
};

const ProjectType = {
  "ROAD_MAINTENANCE": "ROAD_MAINTENANCE",
  "ROAD_DECOMISSION": "ROAD_DECOMISSION",
  "TRAIL_MAINTENANCE": "TRAIL_MAINTENANCE",
  "TRAIL_OBLITERATION": "TRAIL_OBLITERATION",
  "OTHER_INFRASTRUCTURE_MAINTENANCE": "OTHER_INFRASTRUCTURE_MAINTENANCE",
  "SOIL_PRODUCTIVITY_IMPROVEMENT": "SOIL_PRODUCTIVITY_IMPROVEMENT",
  "FOREST_HEALTH_IMPROVEMENT": "FOREST_HEALTH_IMPROVEMENT",
  "WATERSHED_MAINTENANCE": "WATERSHED_MAINTENANCE",
  "WILDLIFE_HABITAT_RESTORATION": "WILDLIFE_HABITAT_RESTORATION",
  "FISH_HABTIAT_RESTORATION": "FISH_HABTIAT_RESTORATION",
  "CONTROL_NOXIOUS_WEEDS": "CONTROL_NOXIOUS_WEEDS",
  "REESTABLISH_NATIVE_SPECIES": "REESTABLISH_NATIVE_SPECIES",
  "FUELS_MANAGEMENT": "FUELS_MANAGEMENT",
  "IMPLEMENT_CWPP_PROJECT": "IMPLEMENT_CWPP_PROJECT",
  "OTHER_PROJECT_TYPE": "OTHER_PROJECT_TYPE"
};

const MeetPurpose = {
  "IMPROVES_MAINTENANCE": "IMPROVES_MAINTENANCE",
  "IMPLEMENT_STEWARDSHIP": "IMPLEMENT_STEWARDSHIP",
  "RESTORES_LANDHEALTH": "RESTORES_LANDHEALTH",
  "RESTORE_WATERQUALITY": "RESTORE_WATERQUALITY"
};

const Land = {
  "STATE": "STATE",
  "PRIVATE": "PRIVATE",
  "OTHER": "OTHER",
  "NONE": "NONE"
};

const ProjectDescription = {
  "SHORT": "SHORT",
  "BRIEF": "BRIEF"
};

const { ProjectAttributes } = initSchema(schema);

export {
  ProjectAttributes,
  FailureRemedies,
  MonitoringPlan,
  ProjectCost,
  AccomplishmentMethods,
  ProjectAccomplishments,
  ProjectType,
  MeetPurpose,
  Land,
  ProjectDescription
};